# gizzmo123456/game_server:server_lobby-1.0
######################

FROM python:3.7.7-alpine3.11

WORKDIR /usr/src/app

ENV PYTHONPATH "${PYTHONPATH}:/usr/src/app"

COPY py_requirements.txt ./
RUN pip install --no-cache-dir -r py_requirements.txt

COPY ./server_lobby.py ./
COPY ./Common/ ./Common/
COPY ./Sockets/ ./Sockets/
COPY ./logs/ ./logs/

CMD [ "python", "-u", "./server_lobby.py" ]