version: "3.7"
# Docker compose file to run all server modules in a single docker instance.

services:  
  server_auth:
    container_name: localhost_auth
    image: gizzmo123456/game_server:server_auth.0.1.0
    working_dir: /services
    volumes:
      - ./:/services
    networks:
      - back-tier
  
  server_lobbies:
    container_name: localhost_lobbies
    image: gizzmo123456/game_server:server_lobbies.0.1.1
    working_dir: /services
    volumes:
      - ./:/services
    networks:
      - back-tier
  
  server_lobby:
    image: gizzmo123456/game_server:server_lobby.0.1.0
    working_dir: /services
    volumes:
      - ./:/services
    networks:
      - back-tier
      
  server_game:
    image: gizzmo123456/game_server:server_game.0.1.0
    working_dir: /services
    volumes:
      - ./:/services
    networks:
      - back-tier
      
  selector:
    image: gizzmo123456/game_server:server_selector.0.1.8
    ports: 
      - 8222:8222
    working_dir: /services
    volumes:
      - ./:/services
    networks:
      - back-tier
               
volumes:
  mysql_db:
    
networks:
  back-tier: