version: "3.7"

services:
  http_anayltics:
    image: http_analytics
    working_dir: /services
    volumes:
      - ./:/services
    networks:
      - back-tier
         
volumes:
  mysql_db:
    
networks:
  front-tier:
  back-tier:
  