version: "3.7"

services:
  sql_setup:
    image: gizzmo123456/game_server:sql_setup.0.1.3
    working_dir: /services
    volumes:
      - ./:/services
    networks:
      - back-tier
  
  sql:
    container_name: localhost_sql
    image: mariadb:10.4.12-bionic
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tb_rpg
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: admin__
      MYSQL_PASSWORD: password1"e
    networks:
      - back-tier
  
  phpMyAddmin:
    container_name: php_my_admin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8081:80
      - 443:443
    environment:
      PMA_HOST: localhost_sql
      PMA_USER: root
      PMA_PASSWORD: password!2E
    volumes:
      - mysql_db:/phpMyAdmin
    networks:
      - back-tier

volumes:
  mysql_db:
    
networks:
  back-tier:
  