version: "3.7"

services:
  sql_setup:
    image: sql_setup:0.1.2
    networks:
      - back-tier
      
  selector:
    image: test_selector:0.1.4
    ports: 
      - 8222:8222
    working_dir: /services
    volumes:
      - ./:/services
    networks:
      - front-tier
      - back-tier

  test_server:
    image: test_server:0.1.2
    working_dir: /services
    volumes:
      - ./:/services
    networks:
      - back-tier
      
  sql:
    container_name: localhost_sql
    image: mariadb:10.4.12-bionic
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password!2E
    networks:
      - back-tier
    
volumes:
  mysql_db:
    
networks:
  front-tier:
  back-tier: